name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_ID = "Ov23liXgCrXMN4POY3R5"
GITHUB_OWNER = "hazelgoughnourmep21-dot"
GITHUB_REPO = "navsphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-demo.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="navsphere-72t.pages.dev"

